---
title: "pMEM fitting"
author: "Dominik Klepl"
date: "6/9/2020"
output:
  pdf_document: default
  html_document: default
---

Libraries
```{r}
#import custom functions
source("scripts/pMEM.R")
```


Read testing data
```{r}
#data = read.table("testdata.dat")
#data = data[,sample(1:ncol(data),1000),]

file = "data/clean_alpha/R38-16_HC_EC.RData"
load(file)
data = t(data)[14:23,]
```

Threshold the data
```{r}
binarized = binarize(data)
```

Check number of unique states
```{r}
#how many combinations are possible?
2^nrow(binarized) 

#unite to form binary states

unique = t(binarized) %>%
  as.data.frame() %>%
  unite("state", sep = "") %>%
  group_by(state) %>%
  summarise(count = n())

ggplot(unique, aes(count))+
  geom_histogram(binwidth = 10)+
  theme_few()+
  labs(x ="Occurences of state")

pastecs::stat.desc(unique$count)
```

## Fit pMEM with pseudo-likelihood

```{r}
param = pMEM_PL(binarized)

#compare pMEM parameters with Pearson's correlation scores
corrplot::corrplot(param$J, method = "color")
corrplot::corrplot(cor(t(data)), method="color")
```

Compare empirical and predicted probabilities
```{r}
probs_emp = get_empirical_prob(binarized)
probs = get_probability(param)
```


Using regression and $R^2$
```{r}
get_R2(probs_emp, probs)
```

+visually
```{r}
data.frame(empirical = probs_emp, predicted = probs) %>%
  ggplot(aes(predicted, empirical))+
  geom_point()+
  theme_few()
```


Test
Sanity check - higher probability means lower energy.
```{r}
data.frame(Probability = get_probability(param),Energy = get_energy(param)) %>%
  ggplot(aes(Probability, Energy))+
  geom_point()+
  theme_few()
```



## Run for all wave bands
```{r}
#based on Rajintha's 
selected_R = c("P3O1", "T6O2", "P4PZ", "T3T5", "F3FZ", "F4C4", "T5O1", "P3PZ", "C3P3", "C4P4")

#posterior
selected_post = c("O1O2", "T5O1", "P3O1", "P4O2", "T6O2", "P3PZ", "P4PZ", "C3P3", "CZPZ", "C4P4")
  
#left
selected_left = c("F7F3", "F3FZ", "F3C3", "C3CZ", "T3C3", "C3P3", "P3PZ", "T3T5", "T5O1", "P3O1")

#rigt
selected_right = c("F8F4", "F4FZ", "F4C4", "C4CZ", "T4C4", "C4P4", "P4PZ", "T4T6", "P4O2", "T6O2")

selections = list(selected_R, selected_post, selected_left, selected_right)
selections_names = c("R", "post", "left", "right")
bands = c("alpha", "beta", "delta", "full", "gamma", "theta")

for (s in 1:length(selections)){
  print(selections_names[s])
  selection = selections[[s]]
  for (b in bands){
    print(b)
    run_folder(wave_band = b, selection = selection, selection_name = selections_names[s])
  }
}
```

Evaluate pMEM fit
```{r}
theta = readr::read_csv("results/pMEM_metrics_theta.csv")

r_theta = lm(r ~ diagnosis+condition, theta)
R2_theta = lm(R2 ~ diagnosis+condition, theta)


theta_summary = theta %>%
  group_by(diagnosis, condition) %>%
  summarise(mean_r = mean(r),
            sd_r = sd(r),
            mean_R2 = mean(R2),
            sd_R2 = sd(R2))

library(patchwork)
r_plot = ggplot(df_summary, aes(x=diagnosis, y = mean_r,fill=diagnosis))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin = mean_r - sd_r, ymax = mean_r + sd_r), width = 0.4)+
  theme_few()+
  scale_fill_tableau()+
  facet_wrap(~condition)+
  labs(x = NULL,
       y = bquote(r[D]))

R2_plot = ggplot(df_summary, aes(x=diagnosis, y = mean_R2,fill=diagnosis))+
  geom_bar(stat="identity")+
  geom_errorbar(aes(ymin = mean_R2 - sd_R2, ymax = mean_R2 + sd_R2), width = 0.4)+
  theme_few()+
  scale_fill_tableau()+
  facet_wrap(~condition)+
  guides(fill=F)+
  labs(x = NULL,
       y = bquote(R^2))

pMEM_plot = r_plot + R2_plot + plot_layout(guides = "collect") + plot_annotation(tag_levels = "A")

ggsave("figures/pMEM_evaluation.png", width = 7, height = 5)
```

