---
title: "04 Results"
author: "Dominik Klepl"
date: "7/9/2020"
output: html_document
---


```{r}
source("scripts/evaluate.R")
```

#Evaluate pMEM fit
Testing whether one group has higher score
```{r}
pMEM_files = list.files("results/pMEM_metrics", full.names = T)
```

```{r}
selections = c("left", "post", "R", "right")

for (s in selections){
  result = merge_results(pMEM_files, s)
  evaluate_pMEM(result, s)
}
```

#Evaluate energy landscape 

## Perform t-tests for each selection-band-condition-feature
Format into tables
```{r}
files = list.files("results/ELA", full.names = T)

#for all features
features = c("minima", "E_diff", "basin_sd", "LMTS_nodes", "LMTS_effective", "duration")

results = list()
for (f in features){
  results[[f]] = test_effect(files = files, feature = f)
}

#save results to csv
for (i in 1:length(results)){
  name = names(results)[i]
  res = results[[name]]
  
  save_to = paste0("results/t-tests/", name, ".csv")
  readr::write_csv(res, save_to)
}
```

### Get shorter tables with only significant results
```{r}
signif_results = list()
for (i in 1:length(results)){
  name = names(results)[i]
  res = results[[name]] %>% 
    filter(`p-value`<=0.05)
  
  signif_results[[name]] = res
  
  save_to = paste0("results/t-tests/signif_", name, ".csv")
  readr::write_csv(res, save_to)
}

save(signif_results, file = "results/backup/signif_results.RData")
```

# Plot the differences
```{r}
plots = list()
names = names(signif_results)
names = names[-4]
for (n in names){
  plots[[n]] = plot_difference(signif_results, n)
}
plots

#save the plots
for (n in names(plots)){
  save_to = paste0("figures/differences/", n, ".png")
  ggsave(save_to, plots[[n]], width = 10, height = 7, dpi = 300)
}
```

